name = "TensorNetworks"
uuid = "bf05fd6d-b814-440f-8e78-cc5435f5625f"
authors = ["Viktor Svensson <svensson.viktor.91@gmail.com>"]
version = "2.0.1"

[deps]
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
SparseArrayKit = "a9a3c162-d163-4c15-8926-b8794fbefed2"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
